#### Importing the Libraries

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### Importing the dataset

In [23]:
df = pd.read_csv(r'D:\machine learning\Machine Learning A-Z Template Folder\Part 8 - Deep Learning\Artificial_Neural_Networks\Churn_Modelling.csv')

In [24]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [25]:
X = df.iloc[:, 3:13].values
y = df.iloc[:, 13].values

In [26]:
X[:5]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

In [27]:
y[:5]

array([1, 0, 1, 0, 0], dtype=int64)

#### Encoding Categorical data

In [29]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [30]:
X[:5]

array([[619, 0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 2, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 0, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 0, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 2, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1]], dtype=object)

In [34]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

In [35]:
X[:5]

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
        0.0000000e+00, 4.2000000e+01, 2.0000000e+00, 0.0000000e+00,
        1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 6.0800000e+02,
        0.0000000e+00, 4.1000000e+01, 1.0000000e+00, 8.3807860e+04,
        1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 5.0200000e+02,
        0.0000000e+00, 4.2000000e+01, 8.0000000e+00, 1.5966080e+05,
        3.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.1393157e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.9900000e+02,
        0.0000000e+00, 3.9000000e+01, 1.0000000e+00, 0.0000000e+00,
        2.0000000e+00, 0.0000000e+00, 0.0000000e+00, 9.3826630e+04],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 8.5000000e+02,
        0.0000000e+00, 4.3000000e+01, 2.0000000e+00, 1.2551082e+05,
        1.0000000e+00, 1.0000000e+00, 1.0000

In [36]:
X = X[:, 1:]

#### Spliiting the dataset

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

#### Feature Scalling

In [38]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [39]:
X_train[:5]

array([[-0.5698444 ,  1.74309049,  0.16958176, -1.09168714, -0.46460796,
         0.00666099, -1.21571749,  0.8095029 ,  0.64259497, -1.03227043,
         1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945,  0.91601335,  0.30102557,
        -1.37744033, -0.00631193, -0.92159124,  0.64259497,  0.9687384 ,
        -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, -1.09168714, -0.94312892,
        -1.031415  ,  0.57993469, -0.92159124,  0.64259497, -1.03227043,
         1.48533467],
       [-0.5698444 ,  1.74309049,  0.03556578,  0.91601335,  0.10961719,
         0.00666099,  0.47312769, -0.92159124,  0.64259497, -1.03227043,
         1.27652776],
       [-0.5698444 ,  1.74309049,  2.05611444, -1.09168714,  1.73658844,
         1.04473698,  0.8101927 ,  0.8095029 ,  0.64259497,  0.9687384 ,
         0.55837842]])

### Building the ANN

In [41]:
import keras
from keras.models import Sequential
from keras.layers import Dense

#### Initializing the Ann

In [42]:
classifier = Sequential()

In [49]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units=6, activation="relu", input_dim=11, kernel_initializer="uniform"))

In [50]:
# Adding the input layer and the second hidden layer
classifier.add(Dense(units=6, activation="relu", kernel_initializer="uniform"))

In [51]:
# Adding the output Layer
classifier.add(Dense(units=1, activation="sigmoid", kernel_initializer="uniform"))

In [52]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [53]:
# Fitting the ANN to the training 
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

C:\Users\aksha\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 2s 199us/step - loss: 0.4808 - acc: 0.7959
Epoch 2/100
8000/8000 [==============================] - 1s 78us/step - loss: 0.4302 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 115us/step - loss: 0.4262 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 77us/step - loss: 0.4208 - acc: 0.8114
Epoch 5/100
8000/8000 [==============================] - 1s 73us/step - loss: 0.4176 - acc: 0.8239
Epoch 6/100
8000/8000 [==============================] - 1s 73us/step - loss: 0.4154 - acc: 0.8249
Epoch 7/100
8000/8000 [==============================] - 1s 72us/step - loss: 0.4135 - acc: 0.8281
Epoch 8/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.4129 - acc: 0.8326
Epoch 9/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.4113 - acc: 0.8306
Epoch 10/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.4101 - acc: 0.8335
Epoch 

8000/8000 [==============================] - 1s 87us/step - loss: 0.3955 - acc: 0.8389
Epoch 83/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.3959 - acc: 0.8386
Epoch 84/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.3951 - acc: 0.8377
Epoch 85/100
8000/8000 [==============================] - 1s 74us/step - loss: 0.3952 - acc: 0.8364
Epoch 86/100
8000/8000 [==============================] - 1s 72us/step - loss: 0.3947 - acc: 0.8381
Epoch 87/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.3952 - acc: 0.8367
Epoch 88/100
8000/8000 [==============================] - 1s 73us/step - loss: 0.3956 - acc: 0.8354
Epoch 89/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.3944 - acc: 0.8379
Epoch 90/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.3947 - acc: 0.8367
Epoch 91/100
8000/8000 [==============================] - 1s 73us/step - loss: 0.3947 - acc: 0.8370
Epoch 92/10

#### Predcting the test set results 

In [54]:
y_pred = classifier.predict(X_test)

In [55]:
y_pred

array([[0.14886425],
       [0.26883796],
       [0.1163324 ],
       ...,
       [0.20862316],
       [0.11325873],
       [0.12550147]], dtype=float32)

In [56]:
y_pred = (y_pred>0.5)

In [57]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

#### Making a Confusion Matrix

In [58]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [59]:
cm

array([[1560,   35],
       [ 278,  127]], dtype=int64)

In [60]:
accuracy = (1560 + 127)/2000

In [61]:
accuracy

0.8435